require: rubocop-rails

AllCops:
    Exclude:
      - 'bin/**/*'
      - 'config/**/*'
      - 'db/**/*'
      - 'lib/**/*'
      - 'node_modules/**/*'
      - 'Rakefile'
      - 'script/**/*'
      - 'spec/factories/**/*'
      - 'spec/rails_helper.rb'
      - 'spec/spec_helper.rb'
Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/AsciiComments: # Let the man shrug! ¯\_(ツ)_/¯
  Enabled: False
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/SymbolArray:
  Enabled: false
